# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_plotly_setting.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1187, 792)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.East)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setGeometry(QtCore.QRect(210, 20, 201, 181))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 20, 201, 28))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_32 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setMinimumSize(QtCore.QSize(65, 0))
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_15.addWidget(self.label_32)
        self.doubleSpinBox_marker_size = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_marker_size.setProperty("value", 5.0)
        self.doubleSpinBox_marker_size.setObjectName("doubleSpinBox_marker_size")
        self.horizontalLayout_15.addWidget(self.doubleSpinBox_marker_size)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 50, 204, 27))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_34 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_17.addWidget(self.label_34)
        self.comboBox_marker_sizemode = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_marker_sizemode.setObjectName("comboBox_marker_sizemode")
        self.comboBox_marker_sizemode.addItem("")
        self.comboBox_marker_sizemode.addItem("")
        self.horizontalLayout_17.addWidget(self.comboBox_marker_sizemode)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 80, 201, 31))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_14.addWidget(self.label_2)
        self.marker_color_Btn = QtWidgets.QPushButton(self.layoutWidget2)
        self.marker_color_Btn.setObjectName("marker_color_Btn")
        self.horizontalLayout_14.addWidget(self.marker_color_Btn)
        self.widget1 = QtWidgets.QWidget(self.groupBox_3)
        self.widget1.setGeometry(QtCore.QRect(0, 150, 201, 27))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_16 = QtWidgets.QLabel(self.widget1)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_33.addWidget(self.label_16)
        self.comboBox_mode = QtWidgets.QComboBox(self.widget1)
        self.comboBox_mode.setObjectName("comboBox_mode")
        self.comboBox_mode.addItem("")
        self.comboBox_mode.addItem("")
        self.comboBox_mode.addItem("")
        self.comboBox_mode.addItem("")
        self.comboBox_mode.addItem("")
        self.horizontalLayout_33.addWidget(self.comboBox_mode)
        self.widget2 = QtWidgets.QWidget(self.groupBox_3)
        self.widget2.setGeometry(QtCore.QRect(0, 120, 201, 28))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_8 = QtWidgets.QLabel(self.widget2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_27.addWidget(self.label_8)
        self.doubleSpinBox_marker_opacity = QtWidgets.QDoubleSpinBox(self.widget2)
        self.doubleSpinBox_marker_opacity.setProperty("value", 1.0)
        self.doubleSpinBox_marker_opacity.setObjectName("doubleSpinBox_marker_opacity")
        self.horizontalLayout_27.addWidget(self.doubleSpinBox_marker_opacity)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setGeometry(QtCore.QRect(210, 200, 201, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 50, 201, 28))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_29 = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_10.addWidget(self.label_29)
        self.doubleSpinBox_line_width = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        self.doubleSpinBox_line_width.setProperty("value", 2.0)
        self.doubleSpinBox_line_width.setObjectName("doubleSpinBox_line_width")
        self.horizontalLayout_10.addWidget(self.doubleSpinBox_line_width)
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget4.setGeometry(QtCore.QRect(0, 80, 201, 27))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_30 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_11.addWidget(self.label_30)
        self.comboBox_line_dash = QtWidgets.QComboBox(self.layoutWidget4)
        self.comboBox_line_dash.setObjectName("comboBox_line_dash")
        self.comboBox_line_dash.addItem("")
        self.comboBox_line_dash.addItem("")
        self.comboBox_line_dash.addItem("")
        self.comboBox_line_dash.addItem("")
        self.comboBox_line_dash.addItem("")
        self.comboBox_line_dash.addItem("")
        self.horizontalLayout_11.addWidget(self.comboBox_line_dash)
        self.layoutWidget5 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget5.setGeometry(QtCore.QRect(0, 20, 208, 33))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_28 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_13.addWidget(self.label_28)
        self.line_color_Btn = QtWidgets.QPushButton(self.layoutWidget5)
        self.line_color_Btn.setObjectName("line_color_Btn")
        self.horizontalLayout_13.addWidget(self.line_color_Btn)
        self.widget3 = QtWidgets.QWidget(self.groupBox_2)
        self.widget3.setGeometry(QtCore.QRect(0, 110, 201, 27))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_26 = QtWidgets.QLabel(self.widget3)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout.addWidget(self.label_26)
        self.comboBox_fill = QtWidgets.QComboBox(self.widget3)
        self.comboBox_fill.setObjectName("comboBox_fill")
        self.comboBox_fill.addItem("")
        self.comboBox_fill.addItem("")
        self.comboBox_fill.addItem("")
        self.comboBox_fill.addItem("")
        self.comboBox_fill.addItem("")
        self.comboBox_fill.addItem("")
        self.comboBox_fill.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_fill)
        self.layoutWidget6 = QtWidgets.QWidget(self.widget)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 180, 180, 33))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_y_data = QtWidgets.QLabel(self.layoutWidget6)
        self.label_y_data.setObjectName("label_y_data")
        self.horizontalLayout_29.addWidget(self.label_y_data)
        self.y_data_Btn = QtWidgets.QPushButton(self.layoutWidget6)
        self.y_data_Btn.setObjectName("y_data_Btn")
        self.horizontalLayout_29.addWidget(self.y_data_Btn)
        self.layoutWidget7 = QtWidgets.QWidget(self.widget)
        self.layoutWidget7.setGeometry(QtCore.QRect(10, 150, 180, 33))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_x_data = QtWidgets.QLabel(self.layoutWidget7)
        self.label_x_data.setObjectName("label_x_data")
        self.horizontalLayout_28.addWidget(self.label_x_data)
        self.x_data_Btn = QtWidgets.QPushButton(self.layoutWidget7)
        self.x_data_Btn.setObjectName("x_data_Btn")
        self.horizontalLayout_28.addWidget(self.x_data_Btn)
        self.layoutWidget8 = QtWidgets.QWidget(self.widget)
        self.layoutWidget8.setGeometry(QtCore.QRect(10, 240, 181, 28))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_24.addWidget(self.label_10)
        self.doubleSpinBox_y0 = QtWidgets.QDoubleSpinBox(self.layoutWidget8)
        self.doubleSpinBox_y0.setObjectName("doubleSpinBox_y0")
        self.horizontalLayout_24.addWidget(self.doubleSpinBox_y0)
        self.layoutWidget9 = QtWidgets.QWidget(self.widget)
        self.layoutWidget9.setGeometry(QtCore.QRect(10, 210, 181, 28))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.layoutWidget9)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_23.addWidget(self.label_11)
        self.doubleSpinBox_x0 = QtWidgets.QDoubleSpinBox(self.layoutWidget9)
        self.doubleSpinBox_x0.setObjectName("doubleSpinBox_x0")
        self.horizontalLayout_23.addWidget(self.doubleSpinBox_x0)
        self.layoutWidget10 = QtWidgets.QWidget(self.widget)
        self.layoutWidget10.setGeometry(QtCore.QRect(10, 270, 181, 28))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget10)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_dx = QtWidgets.QLabel(self.layoutWidget10)
        self.label_dx.setObjectName("label_dx")
        self.horizontalLayout_7.addWidget(self.label_dx)
        self.doubleSpinBox_dx = QtWidgets.QDoubleSpinBox(self.layoutWidget10)
        self.doubleSpinBox_dx.setProperty("value", 1.0)
        self.doubleSpinBox_dx.setObjectName("doubleSpinBox_dx")
        self.horizontalLayout_7.addWidget(self.doubleSpinBox_dx)
        self.layoutWidget11 = QtWidgets.QWidget(self.widget)
        self.layoutWidget11.setGeometry(QtCore.QRect(10, 300, 181, 28))
        self.layoutWidget11.setObjectName("layoutWidget11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget11)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_dy = QtWidgets.QLabel(self.layoutWidget11)
        self.label_dy.setObjectName("label_dy")
        self.horizontalLayout_8.addWidget(self.label_dy)
        self.doubleSpinBox_dy = QtWidgets.QDoubleSpinBox(self.layoutWidget11)
        self.doubleSpinBox_dy.setProperty("value", 1.0)
        self.doubleSpinBox_dy.setObjectName("doubleSpinBox_dy")
        self.horizontalLayout_8.addWidget(self.doubleSpinBox_dy)
        self.layoutWidget12 = QtWidgets.QWidget(self.widget)
        self.layoutWidget12.setGeometry(QtCore.QRect(210, 350, 201, 28))
        self.layoutWidget12.setObjectName("layoutWidget12")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.layoutWidget12)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_20.addWidget(self.label_15)
        self.doubleSpinBox_opacity = QtWidgets.QDoubleSpinBox(self.layoutWidget12)
        self.doubleSpinBox_opacity.setProperty("value", 1.0)
        self.doubleSpinBox_opacity.setObjectName("doubleSpinBox_opacity")
        self.horizontalLayout_20.addWidget(self.doubleSpinBox_opacity)
        self.add_charts_Btn = QtWidgets.QPushButton(self.widget)
        self.add_charts_Btn.setGeometry(QtCore.QRect(100, 110, 89, 25))
        self.add_charts_Btn.setObjectName("add_charts_Btn")
        self.listWidget_charts = QtWidgets.QListWidget(self.widget)
        self.listWidget_charts.setGeometry(QtCore.QRect(0, 10, 191, 91))
        self.listWidget_charts.setObjectName("listWidget_charts")
        self.widget4 = QtWidgets.QWidget(self.widget)
        self.widget4.setGeometry(QtCore.QRect(10, 330, 181, 27))
        self.widget4.setObjectName("widget4")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.widget4)
        self.horizontalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label = QtWidgets.QLabel(self.widget4)
        self.label.setObjectName("label")
        self.horizontalLayout_32.addWidget(self.label)
        self.lineEdit_line_name = QtWidgets.QLineEdit(self.widget4)
        self.lineEdit_line_name.setObjectName("lineEdit_line_name")
        self.horizontalLayout_32.addWidget(self.lineEdit_line_name)
        self.checkBox_scatter_connectgaps = QtWidgets.QCheckBox(self.widget)
        self.checkBox_scatter_connectgaps.setGeometry(QtCore.QRect(10, 370, 141, 23))
        self.checkBox_scatter_connectgaps.setObjectName("checkBox_scatter_connectgaps")
        self.widget5 = QtWidgets.QWidget(self.widget)
        self.widget5.setGeometry(QtCore.QRect(210, 380, 231, 51))
        self.widget5.setObjectName("widget5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget5)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.widget5)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.comboBox_ycalendar = QtWidgets.QComboBox(self.widget5)
        self.comboBox_ycalendar.setObjectName("comboBox_ycalendar")
        self.comboBox_ycalendar.addItem("")
        self.comboBox_ycalendar.addItem("")
        self.comboBox_ycalendar.addItem("")
        self.comboBox_ycalendar.addItem("")
        self.comboBox_ycalendar.addItem("")
        self.comboBox_ycalendar.addItem("")
        self.comboBox_ycalendar.addItem("")
        self.comboBox_ycalendar.addItem("")
        self.comboBox_ycalendar.addItem("")
        self.comboBox_ycalendar.addItem("")
        self.comboBox_ycalendar.addItem("")
        self.comboBox_ycalendar.addItem("")
        self.comboBox_ycalendar.addItem("")
        self.comboBox_ycalendar.addItem("")
        self.comboBox_ycalendar.addItem("")
        self.comboBox_ycalendar.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_ycalendar, 0, 1, 1, 1)
        self.comboBox_xcalendar = QtWidgets.QComboBox(self.widget5)
        self.comboBox_xcalendar.setObjectName("comboBox_xcalendar")
        self.comboBox_xcalendar.addItem("")
        self.comboBox_xcalendar.addItem("")
        self.comboBox_xcalendar.addItem("")
        self.comboBox_xcalendar.addItem("")
        self.comboBox_xcalendar.addItem("")
        self.comboBox_xcalendar.addItem("")
        self.comboBox_xcalendar.addItem("")
        self.comboBox_xcalendar.addItem("")
        self.comboBox_xcalendar.addItem("")
        self.comboBox_xcalendar.addItem("")
        self.comboBox_xcalendar.addItem("")
        self.comboBox_xcalendar.addItem("")
        self.comboBox_xcalendar.addItem("")
        self.comboBox_xcalendar.addItem("")
        self.comboBox_xcalendar.addItem("")
        self.comboBox_xcalendar.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_xcalendar, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget5)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.groupBox_13 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_13.setGeometry(QtCore.QRect(440, 190, 181, 91))
        self.groupBox_13.setObjectName("groupBox_13")
        self.widget6 = QtWidgets.QWidget(self.groupBox_13)
        self.widget6.setGeometry(QtCore.QRect(0, 20, 181, 33))
        self.widget6.setObjectName("widget6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget6)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_17 = QtWidgets.QLabel(self.widget6)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_5.addWidget(self.label_17)
        self.hoverlabel_bgcolor_Btn = QtWidgets.QPushButton(self.widget6)
        self.hoverlabel_bgcolor_Btn.setObjectName("hoverlabel_bgcolor_Btn")
        self.horizontalLayout_5.addWidget(self.hoverlabel_bgcolor_Btn)
        self.widget7 = QtWidgets.QWidget(self.groupBox_13)
        self.widget7.setGeometry(QtCore.QRect(0, 52, 181, 33))
        self.widget7.setObjectName("widget7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget7)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_18 = QtWidgets.QLabel(self.widget7)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_6.addWidget(self.label_18)
        self.hoverlabel_bordercolor_Btn = QtWidgets.QPushButton(self.widget7)
        self.hoverlabel_bordercolor_Btn.setObjectName("hoverlabel_bordercolor_Btn")
        self.horizontalLayout_6.addWidget(self.hoverlabel_bordercolor_Btn)
        self.groupBox_14 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_14.setGeometry(QtCore.QRect(440, 280, 181, 91))
        self.groupBox_14.setObjectName("groupBox_14")
        self.widget8 = QtWidgets.QWidget(self.groupBox_14)
        self.widget8.setGeometry(QtCore.QRect(0, 20, 181, 27))
        self.widget8.setObjectName("widget8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget8)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_19 = QtWidgets.QLabel(self.widget8)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_9.addWidget(self.label_19)
        self.comboBox_hoverlabel_font_family = QtWidgets.QComboBox(self.widget8)
        self.comboBox_hoverlabel_font_family.setObjectName("comboBox_hoverlabel_font_family")
        self.comboBox_hoverlabel_font_family.addItem("")
        self.comboBox_hoverlabel_font_family.addItem("")
        self.comboBox_hoverlabel_font_family.addItem("")
        self.comboBox_hoverlabel_font_family.addItem("")
        self.comboBox_hoverlabel_font_family.addItem("")
        self.comboBox_hoverlabel_font_family.addItem("")
        self.comboBox_hoverlabel_font_family.addItem("")
        self.comboBox_hoverlabel_font_family.addItem("")
        self.comboBox_hoverlabel_font_family.addItem("")
        self.comboBox_hoverlabel_font_family.addItem("")
        self.comboBox_hoverlabel_font_family.addItem("")
        self.comboBox_hoverlabel_font_family.addItem("")
        self.comboBox_hoverlabel_font_family.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox_hoverlabel_font_family)
        self.widget9 = QtWidgets.QWidget(self.groupBox_14)
        self.widget9.setGeometry(QtCore.QRect(1, 51, 181, 33))
        self.widget9.setObjectName("widget9")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.widget9)
        self.horizontalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_22 = QtWidgets.QLabel(self.widget9)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_30.addWidget(self.label_22)
        self.spinBox_hoverlabel_font_size = QtWidgets.QSpinBox(self.widget9)
        self.spinBox_hoverlabel_font_size.setMinimum(1)
        self.spinBox_hoverlabel_font_size.setProperty("value", 15)
        self.spinBox_hoverlabel_font_size.setObjectName("spinBox_hoverlabel_font_size")
        self.horizontalLayout_30.addWidget(self.spinBox_hoverlabel_font_size)
        self.label_25 = QtWidgets.QLabel(self.widget9)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_30.addWidget(self.label_25)
        self.hoverlabel_font_color_Btn = QtWidgets.QPushButton(self.widget9)
        self.hoverlabel_font_color_Btn.setObjectName("hoverlabel_font_color_Btn")
        self.horizontalLayout_30.addWidget(self.hoverlabel_font_color_Btn)
        self.widget10 = QtWidgets.QWidget(self.widget)
        self.widget10.setGeometry(QtCore.QRect(440, 160, 181, 27))
        self.widget10.setObjectName("widget10")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.widget10)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_4 = QtWidgets.QLabel(self.widget10)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_16.addWidget(self.label_4)
        self.lineEdit_text = QtWidgets.QLineEdit(self.widget10)
        self.lineEdit_text.setText("")
        self.lineEdit_text.setObjectName("lineEdit_text")
        self.horizontalLayout_16.addWidget(self.lineEdit_text)
        self.widget11 = QtWidgets.QWidget(self.widget)
        self.widget11.setGeometry(QtCore.QRect(440, 100, 182, 56))
        self.widget11.setObjectName("widget11")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget11)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_20 = QtWidgets.QLabel(self.widget11)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_4.addWidget(self.label_20)
        self.comboBox_hoverinfo = QtWidgets.QComboBox(self.widget11)
        self.comboBox_hoverinfo.setObjectName("comboBox_hoverinfo")
        self.comboBox_hoverinfo.addItem("")
        self.comboBox_hoverinfo.addItem("")
        self.comboBox_hoverinfo.addItem("")
        self.comboBox_hoverinfo.addItem("")
        self.comboBox_hoverinfo.addItem("")
        self.comboBox_hoverinfo.addItem("")
        self.comboBox_hoverinfo.addItem("")
        self.comboBox_hoverinfo.addItem("")
        self.comboBox_hoverinfo.addItem("")
        self.comboBox_hoverinfo.addItem("")
        self.comboBox_hoverinfo.addItem("")
        self.comboBox_hoverinfo.addItem("")
        self.comboBox_hoverinfo.addItem("")
        self.comboBox_hoverinfo.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_hoverinfo)
        self.widget12 = QtWidgets.QWidget(self.widget)
        self.widget12.setGeometry(QtCore.QRect(440, 40, 181, 56))
        self.widget12.setObjectName("widget12")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget12)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_21 = QtWidgets.QLabel(self.widget12)
        self.label_21.setObjectName("label_21")
        self.verticalLayout.addWidget(self.label_21)
        self.comboBox_hoveron = QtWidgets.QComboBox(self.widget12)
        self.comboBox_hoveron.setObjectName("comboBox_hoveron")
        self.comboBox_hoveron.addItem("")
        self.comboBox_hoveron.addItem("")
        self.comboBox_hoveron.addItem("")
        self.verticalLayout.addWidget(self.comboBox_hoveron)
        self.widget13 = QtWidgets.QWidget(self.widget)
        self.widget13.setGeometry(QtCore.QRect(441, 371, 181, 61))
        self.widget13.setObjectName("widget13")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget13)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_14 = QtWidgets.QLabel(self.widget13)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14)
        self.comboBox_textposition = QtWidgets.QComboBox(self.widget13)
        self.comboBox_textposition.setObjectName("comboBox_textposition")
        self.comboBox_textposition.addItem("")
        self.comboBox_textposition.addItem("")
        self.comboBox_textposition.addItem("")
        self.comboBox_textposition.addItem("")
        self.comboBox_textposition.addItem("")
        self.comboBox_textposition.addItem("")
        self.comboBox_textposition.addItem("")
        self.comboBox_textposition.addItem("")
        self.comboBox_textposition.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_textposition)
        self.tabWidget.addTab(self.widget, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 0, 281, 311))
        self.groupBox_5.setObjectName("groupBox_5")
        self.groupBox_15 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_15.setGeometry(QtCore.QRect(0, 50, 221, 101))
        self.groupBox_15.setObjectName("groupBox_15")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_15)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 20, 191, 27))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_18.addWidget(self.label_27)
        self.comboBox_layout_title_font_family = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_layout_title_font_family.setObjectName("comboBox_layout_title_font_family")
        self.comboBox_layout_title_font_family.addItem("")
        self.comboBox_layout_title_font_family.addItem("")
        self.comboBox_layout_title_font_family.addItem("")
        self.comboBox_layout_title_font_family.addItem("")
        self.comboBox_layout_title_font_family.addItem("")
        self.comboBox_layout_title_font_family.addItem("")
        self.comboBox_layout_title_font_family.addItem("")
        self.comboBox_layout_title_font_family.addItem("")
        self.comboBox_layout_title_font_family.addItem("")
        self.comboBox_layout_title_font_family.addItem("")
        self.comboBox_layout_title_font_family.addItem("")
        self.comboBox_layout_title_font_family.addItem("")
        self.comboBox_layout_title_font_family.addItem("")
        self.horizontalLayout_18.addWidget(self.comboBox_layout_title_font_family)
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_15)
        self.layoutWidget_3.setGeometry(QtCore.QRect(1, 51, 209, 33))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_31 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_31.addWidget(self.label_31)
        self.spinBox_layout_title_font_size = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.spinBox_layout_title_font_size.setMinimum(1)
        self.spinBox_layout_title_font_size.setProperty("value", 15)
        self.spinBox_layout_title_font_size.setObjectName("spinBox_layout_title_font_size")
        self.horizontalLayout_31.addWidget(self.spinBox_layout_title_font_size)
        self.label_33 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_31.addWidget(self.label_33)
        self.layout_title_font_color_Btn = QtWidgets.QPushButton(self.layoutWidget_3)
        self.layout_title_font_color_Btn.setObjectName("layout_title_font_color_Btn")
        self.horizontalLayout_31.addWidget(self.layout_title_font_color_Btn)
        self.widget14 = QtWidgets.QWidget(self.groupBox_5)
        self.widget14.setGeometry(QtCore.QRect(0, 20, 161, 27))
        self.widget14.setObjectName("widget14")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget14)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_37 = QtWidgets.QLabel(self.widget14)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_2.addWidget(self.label_37)
        self.lineEdit_layout_title_text = QtWidgets.QLineEdit(self.widget14)
        self.lineEdit_layout_title_text.setObjectName("lineEdit_layout_title_text")
        self.horizontalLayout_2.addWidget(self.lineEdit_layout_title_text)
        self.widget15 = QtWidgets.QWidget(self.groupBox_5)
        self.widget15.setGeometry(QtCore.QRect(10, 190, 175, 28))
        self.widget15.setObjectName("widget15")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget15)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_40 = QtWidgets.QLabel(self.widget15)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_3.addWidget(self.label_40)
        self.doubleSpinBox_layout_title_y = QtWidgets.QDoubleSpinBox(self.widget15)
        self.doubleSpinBox_layout_title_y.setProperty("value", 0.5)
        self.doubleSpinBox_layout_title_y.setObjectName("doubleSpinBox_layout_title_y")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_layout_title_y)
        self.label_39 = QtWidgets.QLabel(self.widget15)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_3.addWidget(self.label_39)
        self.doubleSpinBox_layout_title_x = QtWidgets.QDoubleSpinBox(self.widget15)
        self.doubleSpinBox_layout_title_x.setProperty("value", 0.5)
        self.doubleSpinBox_layout_title_x.setObjectName("doubleSpinBox_layout_title_x")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_layout_title_x)
        self.widget16 = QtWidgets.QWidget(self.groupBox_5)
        self.widget16.setGeometry(QtCore.QRect(0, 230, 278, 27))
        self.widget16.setObjectName("widget16")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget16)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_42 = QtWidgets.QLabel(self.widget16)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_4.addWidget(self.label_42)
        self.comboBox_layout_title_xanchor = QtWidgets.QComboBox(self.widget16)
        self.comboBox_layout_title_xanchor.setObjectName("comboBox_layout_title_xanchor")
        self.comboBox_layout_title_xanchor.addItem("")
        self.comboBox_layout_title_xanchor.addItem("")
        self.comboBox_layout_title_xanchor.addItem("")
        self.comboBox_layout_title_xanchor.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_layout_title_xanchor)
        self.label_41 = QtWidgets.QLabel(self.widget16)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_4.addWidget(self.label_41)
        self.comboBox_layout_title_yanchor = QtWidgets.QComboBox(self.widget16)
        self.comboBox_layout_title_yanchor.setObjectName("comboBox_layout_title_yanchor")
        self.comboBox_layout_title_yanchor.addItem("")
        self.comboBox_layout_title_yanchor.addItem("")
        self.comboBox_layout_title_yanchor.addItem("")
        self.comboBox_layout_title_yanchor.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_layout_title_yanchor)
        self.widget17 = QtWidgets.QWidget(self.groupBox_5)
        self.widget17.setGeometry(QtCore.QRect(10, 270, 120, 33))
        self.widget17.setObjectName("widget17")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.widget17)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_3 = QtWidgets.QLabel(self.widget17)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_19.addWidget(self.label_3)
        self.comboBox_layout_title_pad = QtWidgets.QComboBox(self.widget17)
        self.comboBox_layout_title_pad.setObjectName("comboBox_layout_title_pad")
        self.comboBox_layout_title_pad.addItem("")
        self.comboBox_layout_title_pad.addItem("")
        self.comboBox_layout_title_pad.addItem("")
        self.comboBox_layout_title_pad.addItem("")
        self.horizontalLayout_19.addWidget(self.comboBox_layout_title_pad)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setGeometry(QtCore.QRect(250, 20, 301, 91))
        self.groupBox_7.setObjectName("groupBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_8.setGeometry(QtCore.QRect(130, 60, 111, 23))
        self.checkBox_8.setObjectName("checkBox_8")
        self.widget18 = QtWidgets.QWidget(self.groupBox_7)
        self.widget18.setGeometry(QtCore.QRect(0, 30, 301, 28))
        self.widget18.setObjectName("widget18")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.widget18)
        self.horizontalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_52 = QtWidgets.QLabel(self.widget18)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_36.addWidget(self.label_52)
        self.spinBox = QtWidgets.QSpinBox(self.widget18)
        self.spinBox.setMaximum(999999)
        self.spinBox.setProperty("value", 100)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_36.addWidget(self.spinBox)
        self.label_53 = QtWidgets.QLabel(self.widget18)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_36.addWidget(self.label_53)
        self.spinBox_2 = QtWidgets.QSpinBox(self.widget18)
        self.spinBox_2.setProperty("value", 80)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_36.addWidget(self.spinBox_2)
        self.label_54 = QtWidgets.QLabel(self.widget18)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_36.addWidget(self.label_54)
        self.spinBox_3 = QtWidgets.QSpinBox(self.widget18)
        self.spinBox_3.setProperty("value", 80)
        self.spinBox_3.setObjectName("spinBox_3")
        self.horizontalLayout_36.addWidget(self.spinBox_3)
        self.label_55 = QtWidgets.QLabel(self.widget18)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_36.addWidget(self.label_55)
        self.spinBox_4 = QtWidgets.QSpinBox(self.widget18)
        self.spinBox_4.setProperty("value", 80)
        self.spinBox_4.setObjectName("spinBox_4")
        self.horizontalLayout_36.addWidget(self.spinBox_4)
        self.widget19 = QtWidgets.QWidget(self.groupBox_7)
        self.widget19.setGeometry(QtCore.QRect(10, 60, 82, 28))
        self.widget19.setObjectName("widget19")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.widget19)
        self.horizontalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_56 = QtWidgets.QLabel(self.widget19)
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_37.addWidget(self.label_56)
        self.spinBox_5 = QtWidgets.QSpinBox(self.widget19)
        self.spinBox_5.setObjectName("spinBox_5")
        self.horizontalLayout_37.addWidget(self.spinBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(590, 70, 181, 121))
        self.groupBox_6.setObjectName("groupBox_6")
        self.widget20 = QtWidgets.QWidget(self.groupBox_6)
        self.widget20.setGeometry(QtCore.QRect(0, 20, 175, 28))
        self.widget20.setObjectName("widget20")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.widget20)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_43 = QtWidgets.QLabel(self.widget20)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_21.addWidget(self.label_43)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.widget20)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.horizontalLayout_21.addWidget(self.doubleSpinBox_4)
        self.label_44 = QtWidgets.QLabel(self.widget20)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_21.addWidget(self.label_44)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.widget20)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.horizontalLayout_21.addWidget(self.doubleSpinBox_3)
        self.widget21 = QtWidgets.QWidget(self.groupBox_6)
        self.widget21.setGeometry(QtCore.QRect(0, 50, 178, 27))
        self.widget21.setObjectName("widget21")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.widget21)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_45 = QtWidgets.QLabel(self.widget21)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_22.addWidget(self.label_45)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget21)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_22.addWidget(self.pushButton_2)
        self.widget22 = QtWidgets.QWidget(self.groupBox_6)
        self.widget22.setGeometry(QtCore.QRect(0, 80, 163, 28))
        self.widget22.setObjectName("widget22")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.widget22)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_46 = QtWidgets.QLabel(self.widget22)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_25.addWidget(self.label_46)
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.widget22)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.horizontalLayout_25.addWidget(self.doubleSpinBox_5)
        self.comboBox_11 = QtWidgets.QComboBox(self.tab)
        self.comboBox_11.setGeometry(QtCore.QRect(720, 10, 86, 25))
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_8.setGeometry(QtCore.QRect(0, 320, 1121, 451))
        self.groupBox_8.setObjectName("groupBox_8")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox.setGeometry(QtCore.QRect(10, 110, 92, 23))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 130, 92, 23))
        self.checkBox_2.setObjectName("checkBox_2")
        self.label_66 = QtWidgets.QLabel(self.groupBox_8)
        self.label_66.setGeometry(QtCore.QRect(10, 230, 81, 17))
        self.label_66.setObjectName("label_66")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_3.setGeometry(QtCore.QRect(310, 80, 92, 23))
        self.checkBox_3.setObjectName("checkBox_3")
        self.label_72 = QtWidgets.QLabel(self.groupBox_8)
        self.label_72.setGeometry(QtCore.QRect(320, 190, 67, 17))
        self.label_72.setObjectName("label_72")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_5.setGeometry(QtCore.QRect(320, 250, 92, 23))
        self.checkBox_5.setObjectName("checkBox_5")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_9.setGeometry(QtCore.QRect(590, 30, 201, 341))
        self.groupBox_9.setObjectName("groupBox_9")
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_6.setGeometry(QtCore.QRect(10, 90, 92, 23))
        self.checkBox_6.setObjectName("checkBox_6")
        self.label_80 = QtWidgets.QLabel(self.groupBox_9)
        self.label_80.setGeometry(QtCore.QRect(0, 110, 67, 17))
        self.label_80.setObjectName("label_80")
        self.checkBox_11 = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_11.setGeometry(QtCore.QRect(0, 150, 92, 23))
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_12.setGeometry(QtCore.QRect(0, 182, 41, 21))
        self.checkBox_12.setObjectName("checkBox_12")
        self.widget23 = QtWidgets.QWidget(self.groupBox_9)
        self.widget23.setGeometry(QtCore.QRect(0, 20, 149, 27))
        self.widget23.setObjectName("widget23")
        self.horizontalLayout_58 = QtWidgets.QHBoxLayout(self.widget23)
        self.horizontalLayout_58.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_58.setObjectName("horizontalLayout_58")
        self.label_77 = QtWidgets.QLabel(self.widget23)
        self.label_77.setObjectName("label_77")
        self.horizontalLayout_58.addWidget(self.label_77)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget23)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_58.addWidget(self.pushButton_9)
        self.widget24 = QtWidgets.QWidget(self.groupBox_9)
        self.widget24.setGeometry(QtCore.QRect(0, 50, 178, 27))
        self.widget24.setObjectName("widget24")
        self.horizontalLayout_59 = QtWidgets.QHBoxLayout(self.widget24)
        self.horizontalLayout_59.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        self.label_78 = QtWidgets.QLabel(self.widget24)
        self.label_78.setObjectName("label_78")
        self.horizontalLayout_59.addWidget(self.label_78)
        self.pushButton_10 = QtWidgets.QPushButton(self.widget24)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_59.addWidget(self.pushButton_10)
        self.widget25 = QtWidgets.QWidget(self.groupBox_9)
        self.widget25.setGeometry(QtCore.QRect(10, 70, 163, 28))
        self.widget25.setObjectName("widget25")
        self.horizontalLayout_60 = QtWidgets.QHBoxLayout(self.widget25)
        self.horizontalLayout_60.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_60.setObjectName("horizontalLayout_60")
        self.label_79 = QtWidgets.QLabel(self.widget25)
        self.label_79.setObjectName("label_79")
        self.horizontalLayout_60.addWidget(self.label_79)
        self.doubleSpinBox_11 = QtWidgets.QDoubleSpinBox(self.widget25)
        self.doubleSpinBox_11.setObjectName("doubleSpinBox_11")
        self.horizontalLayout_60.addWidget(self.doubleSpinBox_11)
        self.widget26 = QtWidgets.QWidget(self.groupBox_9)
        self.widget26.setGeometry(QtCore.QRect(0, 210, 141, 28))
        self.widget26.setObjectName("widget26")
        self.horizontalLayout_61 = QtWidgets.QHBoxLayout(self.widget26)
        self.horizontalLayout_61.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_61.setObjectName("horizontalLayout_61")
        self.label_81 = QtWidgets.QLabel(self.widget26)
        self.label_81.setObjectName("label_81")
        self.horizontalLayout_61.addWidget(self.label_81)
        self.doubleSpinBox_12 = QtWidgets.QDoubleSpinBox(self.widget26)
        self.doubleSpinBox_12.setProperty("value", 0.15)
        self.doubleSpinBox_12.setObjectName("doubleSpinBox_12")
        self.horizontalLayout_61.addWidget(self.doubleSpinBox_12)
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_10.setGeometry(QtCore.QRect(800, 40, 301, 421))
        self.groupBox_10.setObjectName("groupBox_10")
        self.label_84 = QtWidgets.QLabel(self.groupBox_10)
        self.label_84.setGeometry(QtCore.QRect(0, 20, 67, 17))
        self.label_84.setObjectName("label_84")
        self.label_85 = QtWidgets.QLabel(self.groupBox_10)
        self.label_85.setGeometry(QtCore.QRect(0, 40, 67, 17))
        self.label_85.setObjectName("label_85")
        self.label_86 = QtWidgets.QLabel(self.groupBox_10)
        self.label_86.setGeometry(QtCore.QRect(60, 200, 21, 17))
        self.label_86.setObjectName("label_86")
        self.label_87 = QtWidgets.QLabel(self.groupBox_10)
        self.label_87.setGeometry(QtCore.QRect(10, 200, 21, 17))
        self.label_87.setObjectName("label_87")
        self.label_91 = QtWidgets.QLabel(self.groupBox_10)
        self.label_91.setGeometry(QtCore.QRect(180, 230, 67, 17))
        self.label_91.setObjectName("label_91")
        self.label_92 = QtWidgets.QLabel(self.groupBox_10)
        self.label_92.setGeometry(QtCore.QRect(150, 200, 67, 17))
        self.label_92.setObjectName("label_92")
        self.label_93 = QtWidgets.QLabel(self.groupBox_10)
        self.label_93.setGeometry(QtCore.QRect(90, 200, 67, 17))
        self.label_93.setObjectName("label_93")
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_11.setGeometry(QtCore.QRect(0, 60, 291, 131))
        self.groupBox_11.setObjectName("groupBox_11")
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox_11)
        self.checkBox_7.setGeometry(QtCore.QRect(0, 20, 92, 23))
        self.checkBox_7.setObjectName("checkBox_7")
        self.widget27 = QtWidgets.QWidget(self.groupBox_11)
        self.widget27.setGeometry(QtCore.QRect(0, 100, 184, 27))
        self.widget27.setObjectName("widget27")
        self.horizontalLayout_65 = QtWidgets.QHBoxLayout(self.widget27)
        self.horizontalLayout_65.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_65.setObjectName("horizontalLayout_65")
        self.label_97 = QtWidgets.QLabel(self.widget27)
        self.label_97.setObjectName("label_97")
        self.horizontalLayout_65.addWidget(self.label_97)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget27)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_65.addWidget(self.lineEdit_5)
        self.widget28 = QtWidgets.QWidget(self.groupBox_11)
        self.widget28.setGeometry(QtCore.QRect(0, 70, 172, 27))
        self.widget28.setObjectName("widget28")
        self.horizontalLayout_66 = QtWidgets.QHBoxLayout(self.widget28)
        self.horizontalLayout_66.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_66.setObjectName("horizontalLayout_66")
        self.label_96 = QtWidgets.QLabel(self.widget28)
        self.label_96.setObjectName("label_96")
        self.horizontalLayout_66.addWidget(self.label_96)
        self.comboBox_17 = QtWidgets.QComboBox(self.widget28)
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.horizontalLayout_66.addWidget(self.comboBox_17)
        self.widget29 = QtWidgets.QWidget(self.groupBox_11)
        self.widget29.setGeometry(QtCore.QRect(160, 40, 95, 28))
        self.widget29.setObjectName("widget29")
        self.horizontalLayout_67 = QtWidgets.QHBoxLayout(self.widget29)
        self.horizontalLayout_67.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_67.setObjectName("horizontalLayout_67")
        self.label_95 = QtWidgets.QLabel(self.widget29)
        self.label_95.setObjectName("label_95")
        self.horizontalLayout_67.addWidget(self.label_95)
        self.spinBox_8 = QtWidgets.QSpinBox(self.widget29)
        self.spinBox_8.setObjectName("spinBox_8")
        self.horizontalLayout_67.addWidget(self.spinBox_8)
        self.widget30 = QtWidgets.QWidget(self.groupBox_11)
        self.widget30.setGeometry(QtCore.QRect(0, 40, 116, 27))
        self.widget30.setObjectName("widget30")
        self.horizontalLayout_68 = QtWidgets.QHBoxLayout(self.widget30)
        self.horizontalLayout_68.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_68.setObjectName("horizontalLayout_68")
        self.label_94 = QtWidgets.QLabel(self.widget30)
        self.label_94.setObjectName("label_94")
        self.horizontalLayout_68.addWidget(self.label_94)
        self.comboBox_16 = QtWidgets.QComboBox(self.widget30)
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.horizontalLayout_68.addWidget(self.comboBox_16)
        self.widget31 = QtWidgets.QWidget(self.groupBox_10)
        self.widget31.setGeometry(QtCore.QRect(0, 260, 163, 28))
        self.widget31.setObjectName("widget31")
        self.horizontalLayout_62 = QtWidgets.QHBoxLayout(self.widget31)
        self.horizontalLayout_62.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_62.setObjectName("horizontalLayout_62")
        self.label_88 = QtWidgets.QLabel(self.widget31)
        self.label_88.setObjectName("label_88")
        self.horizontalLayout_62.addWidget(self.label_88)
        self.doubleSpinBox_13 = QtWidgets.QDoubleSpinBox(self.widget31)
        self.doubleSpinBox_13.setObjectName("doubleSpinBox_13")
        self.horizontalLayout_62.addWidget(self.doubleSpinBox_13)
        self.widget32 = QtWidgets.QWidget(self.groupBox_10)
        self.widget32.setGeometry(QtCore.QRect(0, 230, 178, 27))
        self.widget32.setObjectName("widget32")
        self.horizontalLayout_63 = QtWidgets.QHBoxLayout(self.widget32)
        self.horizontalLayout_63.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_63.setObjectName("horizontalLayout_63")
        self.label_89 = QtWidgets.QLabel(self.widget32)
        self.label_89.setObjectName("label_89")
        self.horizontalLayout_63.addWidget(self.label_89)
        self.pushButton_11 = QtWidgets.QPushButton(self.widget32)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_63.addWidget(self.pushButton_11)
        self.widget33 = QtWidgets.QWidget(self.groupBox_10)
        self.widget33.setGeometry(QtCore.QRect(10, 290, 149, 27))
        self.widget33.setObjectName("widget33")
        self.horizontalLayout_64 = QtWidgets.QHBoxLayout(self.widget33)
        self.horizontalLayout_64.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_64.setObjectName("horizontalLayout_64")
        self.label_90 = QtWidgets.QLabel(self.widget33)
        self.label_90.setObjectName("label_90")
        self.horizontalLayout_64.addWidget(self.label_90)
        self.pushButton_12 = QtWidgets.QPushButton(self.widget33)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_64.addWidget(self.pushButton_12)
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_9.setGeometry(QtCore.QRect(10, 20, 92, 23))
        self.checkBox_9.setObjectName("checkBox_9")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox.setGeometry(QtCore.QRect(150, 30, 141, 161))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_16 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_16.setGeometry(QtCore.QRect(10, 60, 121, 91))
        self.groupBox_16.setObjectName("groupBox_16")
        self.layoutWidget_4 = QtWidgets.QWidget(self.groupBox_16)
        self.layoutWidget_4.setGeometry(QtCore.QRect(0, 20, 205, 27))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_41.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.label_35 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_41.addWidget(self.label_35)
        self.comboBox_hoverlabel_font_family_3 = QtWidgets.QComboBox(self.layoutWidget_4)
        self.comboBox_hoverlabel_font_family_3.setObjectName("comboBox_hoverlabel_font_family_3")
        self.comboBox_hoverlabel_font_family_3.addItem("")
        self.comboBox_hoverlabel_font_family_3.addItem("")
        self.comboBox_hoverlabel_font_family_3.addItem("")
        self.comboBox_hoverlabel_font_family_3.addItem("")
        self.comboBox_hoverlabel_font_family_3.addItem("")
        self.comboBox_hoverlabel_font_family_3.addItem("")
        self.comboBox_hoverlabel_font_family_3.addItem("")
        self.comboBox_hoverlabel_font_family_3.addItem("")
        self.comboBox_hoverlabel_font_family_3.addItem("")
        self.comboBox_hoverlabel_font_family_3.addItem("")
        self.comboBox_hoverlabel_font_family_3.addItem("")
        self.comboBox_hoverlabel_font_family_3.addItem("")
        self.comboBox_hoverlabel_font_family_3.addItem("")
        self.horizontalLayout_41.addWidget(self.comboBox_hoverlabel_font_family_3)
        self.layoutWidget_5 = QtWidgets.QWidget(self.groupBox_16)
        self.layoutWidget_5.setGeometry(QtCore.QRect(1, 51, 209, 33))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_42.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.label_36 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_42.addWidget(self.label_36)
        self.spinBox_hoverlabel_font_size_3 = QtWidgets.QSpinBox(self.layoutWidget_5)
        self.spinBox_hoverlabel_font_size_3.setMinimum(1)
        self.spinBox_hoverlabel_font_size_3.setProperty("value", 15)
        self.spinBox_hoverlabel_font_size_3.setObjectName("spinBox_hoverlabel_font_size_3")
        self.horizontalLayout_42.addWidget(self.spinBox_hoverlabel_font_size_3)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_42.addWidget(self.label_38)
        self.hoverlabel_font_color_Btn_3 = QtWidgets.QPushButton(self.layoutWidget_5)
        self.hoverlabel_font_color_Btn_3.setObjectName("hoverlabel_font_color_Btn_3")
        self.horizontalLayout_42.addWidget(self.hoverlabel_font_color_Btn_3)
        self.widget34 = QtWidgets.QWidget(self.groupBox)
        self.widget34.setGeometry(QtCore.QRect(0, 20, 111, 27))
        self.widget34.setObjectName("widget34")
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout(self.widget34)
        self.horizontalLayout_40.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.label_9 = QtWidgets.QLabel(self.widget34)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_40.addWidget(self.label_9)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget34)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_40.addWidget(self.lineEdit_2)
        self.checkBox_10 = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_10.setGeometry(QtCore.QRect(180, 270, 131, 23))
        self.checkBox_10.setObjectName("checkBox_10")
        self.widget35 = QtWidgets.QWidget(self.groupBox_8)
        self.widget35.setGeometry(QtCore.QRect(420, 70, 132, 27))
        self.widget35.setObjectName("widget35")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout(self.widget35)
        self.horizontalLayout_39.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_5 = QtWidgets.QLabel(self.widget35)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_39.addWidget(self.label_5)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget35)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_39.addWidget(self.pushButton_5)
        self.widget36 = QtWidgets.QWidget(self.groupBox_8)
        self.widget36.setGeometry(QtCore.QRect(10, 40, 131, 27))
        self.widget36.setObjectName("widget36")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout(self.widget36)
        self.horizontalLayout_43.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.label_59 = QtWidgets.QLabel(self.widget36)
        self.label_59.setObjectName("label_59")
        self.horizontalLayout_43.addWidget(self.label_59)
        self.comboBox_4 = QtWidgets.QComboBox(self.widget36)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.horizontalLayout_43.addWidget(self.comboBox_4)
        self.widget37 = QtWidgets.QWidget(self.groupBox_8)
        self.widget37.setGeometry(QtCore.QRect(150, 200, 141, 27))
        self.widget37.setObjectName("widget37")
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout(self.widget37)
        self.horizontalLayout_44.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.label_60 = QtWidgets.QLabel(self.widget37)
        self.label_60.setObjectName("label_60")
        self.horizontalLayout_44.addWidget(self.label_60)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget37)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_44.addWidget(self.lineEdit_3)
        self.widget38 = QtWidgets.QWidget(self.groupBox_8)
        self.widget38.setGeometry(QtCore.QRect(150, 230, 131, 27))
        self.widget38.setObjectName("widget38")
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout(self.widget38)
        self.horizontalLayout_45.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.label_61 = QtWidgets.QLabel(self.widget38)
        self.label_61.setObjectName("label_61")
        self.horizontalLayout_45.addWidget(self.label_61)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget38)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_45.addWidget(self.lineEdit_4)
        self.widget39 = QtWidgets.QWidget(self.groupBox_8)
        self.widget39.setGeometry(QtCore.QRect(10, 70, 141, 27))
        self.widget39.setObjectName("widget39")
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout(self.widget39)
        self.horizontalLayout_46.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.label_62 = QtWidgets.QLabel(self.widget39)
        self.label_62.setObjectName("label_62")
        self.horizontalLayout_46.addWidget(self.label_62)
        self.comboBox_12 = QtWidgets.QComboBox(self.widget39)
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.horizontalLayout_46.addWidget(self.comboBox_12)
        self.widget40 = QtWidgets.QWidget(self.groupBox_8)
        self.widget40.setGeometry(QtCore.QRect(10, 160, 121, 27))
        self.widget40.setObjectName("widget40")
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout(self.widget40)
        self.horizontalLayout_47.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.label_63 = QtWidgets.QLabel(self.widget40)
        self.label_63.setObjectName("label_63")
        self.horizontalLayout_47.addWidget(self.label_63)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget40)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_47.addWidget(self.pushButton_6)
        self.widget41 = QtWidgets.QWidget(self.groupBox_8)
        self.widget41.setGeometry(QtCore.QRect(10, 190, 141, 28))
        self.widget41.setObjectName("widget41")
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout(self.widget41)
        self.horizontalLayout_48.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.label_64 = QtWidgets.QLabel(self.widget41)
        self.label_64.setObjectName("label_64")
        self.horizontalLayout_48.addWidget(self.label_64)
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.widget41)
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.horizontalLayout_48.addWidget(self.doubleSpinBox_8)
        self.widget42 = QtWidgets.QWidget(self.groupBox_8)
        self.widget42.setGeometry(QtCore.QRect(0, 260, 165, 27))
        self.widget42.setObjectName("widget42")
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout(self.widget42)
        self.horizontalLayout_49.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.label_67 = QtWidgets.QLabel(self.widget42)
        self.label_67.setObjectName("label_67")
        self.horizontalLayout_49.addWidget(self.label_67)
        self.comboBox_13 = QtWidgets.QComboBox(self.widget42)
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.horizontalLayout_49.addWidget(self.comboBox_13)
        self.widget43 = QtWidgets.QWidget(self.groupBox_8)
        self.widget43.setGeometry(QtCore.QRect(320, 50, 116, 27))
        self.widget43.setObjectName("widget43")
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout(self.widget43)
        self.horizontalLayout_50.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.label_68 = QtWidgets.QLabel(self.widget43)
        self.label_68.setObjectName("label_68")
        self.horizontalLayout_50.addWidget(self.label_68)
        self.comboBox_14 = QtWidgets.QComboBox(self.widget43)
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.horizontalLayout_50.addWidget(self.comboBox_14)
        self.widget44 = QtWidgets.QWidget(self.groupBox_8)
        self.widget44.setGeometry(QtCore.QRect(310, 100, 186, 27))
        self.widget44.setObjectName("widget44")
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout(self.widget44)
        self.horizontalLayout_51.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.checkBox_4 = QtWidgets.QCheckBox(self.widget44)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_51.addWidget(self.checkBox_4)
        self.comboBox_15 = QtWidgets.QComboBox(self.widget44)
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_15.addItem("")
        self.comboBox_15.setItemText(0, "")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.horizontalLayout_51.addWidget(self.comboBox_15)
        self.widget45 = QtWidgets.QWidget(self.groupBox_8)
        self.widget45.setGeometry(QtCore.QRect(460, 130, 123, 31))
        self.widget45.setObjectName("widget45")
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout(self.widget45)
        self.horizontalLayout_52.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.label_69 = QtWidgets.QLabel(self.widget45)
        self.label_69.setObjectName("label_69")
        self.horizontalLayout_52.addWidget(self.label_69)
        self.doubleSpinBox_9 = QtWidgets.QDoubleSpinBox(self.widget45)
        self.doubleSpinBox_9.setProperty("value", 5.0)
        self.doubleSpinBox_9.setObjectName("doubleSpinBox_9")
        self.horizontalLayout_52.addWidget(self.doubleSpinBox_9)
        self.widget46 = QtWidgets.QWidget(self.groupBox_8)
        self.widget46.setGeometry(QtCore.QRect(300, 130, 141, 28))
        self.widget46.setObjectName("widget46")
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout(self.widget46)
        self.horizontalLayout_53.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        self.label_70 = QtWidgets.QLabel(self.widget46)
        self.label_70.setObjectName("label_70")
        self.horizontalLayout_53.addWidget(self.label_70)
        self.doubleSpinBox_10 = QtWidgets.QDoubleSpinBox(self.widget46)
        self.doubleSpinBox_10.setProperty("value", 1.0)
        self.doubleSpinBox_10.setObjectName("doubleSpinBox_10")
        self.horizontalLayout_53.addWidget(self.doubleSpinBox_10)
        self.widget47 = QtWidgets.QWidget(self.groupBox_8)
        self.widget47.setGeometry(QtCore.QRect(320, 160, 156, 27))
        self.widget47.setObjectName("widget47")
        self.horizontalLayout_54 = QtWidgets.QHBoxLayout(self.widget47)
        self.horizontalLayout_54.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_54.setObjectName("horizontalLayout_54")
        self.label_71 = QtWidgets.QLabel(self.widget47)
        self.label_71.setObjectName("label_71")
        self.horizontalLayout_54.addWidget(self.label_71)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget47)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_54.addWidget(self.pushButton_7)
        self.widget48 = QtWidgets.QWidget(self.groupBox_8)
        self.widget48.setGeometry(QtCore.QRect(320, 200, 96, 28))
        self.widget48.setObjectName("widget48")
        self.horizontalLayout_55 = QtWidgets.QHBoxLayout(self.widget48)
        self.horizontalLayout_55.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_55.setObjectName("horizontalLayout_55")
        self.label_73 = QtWidgets.QLabel(self.widget48)
        self.label_73.setObjectName("label_73")
        self.horizontalLayout_55.addWidget(self.label_73)
        self.spinBox_6 = QtWidgets.QSpinBox(self.widget48)
        self.spinBox_6.setObjectName("spinBox_6")
        self.horizontalLayout_55.addWidget(self.spinBox_6)
        self.widget49 = QtWidgets.QWidget(self.groupBox_8)
        self.widget49.setGeometry(QtCore.QRect(330, 270, 159, 27))
        self.widget49.setObjectName("widget49")
        self.horizontalLayout_56 = QtWidgets.QHBoxLayout(self.widget49)
        self.horizontalLayout_56.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_56.setObjectName("horizontalLayout_56")
        self.label_75 = QtWidgets.QLabel(self.widget49)
        self.label_75.setObjectName("label_75")
        self.horizontalLayout_56.addWidget(self.label_75)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget49)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_56.addWidget(self.pushButton_8)
        self.widget50 = QtWidgets.QWidget(self.groupBox_8)
        self.widget50.setGeometry(QtCore.QRect(430, 200, 122, 28))
        self.widget50.setObjectName("widget50")
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout(self.widget50)
        self.horizontalLayout_57.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.label_76 = QtWidgets.QLabel(self.widget50)
        self.label_76.setObjectName("label_76")
        self.horizontalLayout_57.addWidget(self.label_76)
        self.spinBox_7 = QtWidgets.QSpinBox(self.widget50)
        self.spinBox_7.setObjectName("spinBox_7")
        self.horizontalLayout_57.addWidget(self.spinBox_7)
        self.widget51 = QtWidgets.QWidget(self.tab)
        self.widget51.setGeometry(QtCore.QRect(260, 130, 241, 28))
        self.widget51.setObjectName("widget51")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.widget51)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_48 = QtWidgets.QLabel(self.widget51)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_26.addWidget(self.label_48)
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.widget51)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.horizontalLayout_26.addWidget(self.doubleSpinBox_6)
        self.label_47 = QtWidgets.QLabel(self.widget51)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_26.addWidget(self.label_47)
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.widget51)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.horizontalLayout_26.addWidget(self.doubleSpinBox_7)
        self.widget52 = QtWidgets.QWidget(self.tab)
        self.widget52.setGeometry(QtCore.QRect(280, 160, 196, 27))
        self.widget52.setObjectName("widget52")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.widget52)
        self.horizontalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_49 = QtWidgets.QLabel(self.widget52)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_34.addWidget(self.label_49)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget52)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_34.addWidget(self.pushButton_3)
        self.widget53 = QtWidgets.QWidget(self.tab)
        self.widget53.setGeometry(QtCore.QRect(280, 190, 184, 27))
        self.widget53.setObjectName("widget53")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.widget53)
        self.horizontalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_50 = QtWidgets.QLabel(self.widget53)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_35.addWidget(self.label_50)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget53)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_35.addWidget(self.pushButton_4)
        self.widget54 = QtWidgets.QWidget(self.tab)
        self.widget54.setGeometry(QtCore.QRect(280, 220, 173, 27))
        self.widget54.setObjectName("widget54")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout(self.widget54)
        self.horizontalLayout_38.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_58 = QtWidgets.QLabel(self.widget54)
        self.label_58.setObjectName("label_58")
        self.horizontalLayout_38.addWidget(self.label_58)
        self.comboBox_3 = QtWidgets.QComboBox(self.widget54)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout_38.addWidget(self.comboBox_3)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.confirm_Btn = QtWidgets.QPushButton(Form)
        self.confirm_Btn.setObjectName("confirm_Btn")
        self.horizontalLayout_12.addWidget(self.confirm_Btn)
        self.preview_Btn = QtWidgets.QPushButton(Form)
        self.preview_Btn.setObjectName("preview_Btn")
        self.horizontalLayout_12.addWidget(self.preview_Btn)
        self.cancel_Btn = QtWidgets.QPushButton(Form)
        self.cancel_Btn.setObjectName("cancel_Btn")
        self.horizontalLayout_12.addWidget(self.cancel_Btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "绘图设置"))
        self.groupBox_3.setTitle(_translate("Form", "数据节点参数"))
        self.label_32.setText(_translate("Form", "size"))
        self.label_34.setText(_translate("Form", "sizemode"))
        self.comboBox_marker_sizemode.setItemText(0, _translate("Form", "diameter(直径)"))
        self.comboBox_marker_sizemode.setItemText(1, _translate("Form", "area(面积)"))
        self.label_2.setText(_translate("Form", "color"))
        self.marker_color_Btn.setText(_translate("Form", "选择"))
        self.label_16.setText(_translate("Form", "图形格式"))
        self.comboBox_mode.setItemText(0, _translate("Form", "line"))
        self.comboBox_mode.setItemText(1, _translate("Form", "markers"))
        self.comboBox_mode.setItemText(2, _translate("Form", "lines+markers"))
        self.comboBox_mode.setItemText(3, _translate("Form", "lines+markers+text"))
        self.comboBox_mode.setItemText(4, _translate("Form", "none"))
        self.label_8.setText(_translate("Form", "opacity"))
        self.groupBox_2.setTitle(_translate("Form", "线条参数"))
        self.label_29.setText(_translate("Form", "线条宽度"))
        self.label_30.setText(_translate("Form", "线条格式"))
        self.comboBox_line_dash.setItemText(0, _translate("Form", "solid"))
        self.comboBox_line_dash.setItemText(1, _translate("Form", "dash"))
        self.comboBox_line_dash.setItemText(2, _translate("Form", "dot"))
        self.comboBox_line_dash.setItemText(3, _translate("Form", "longdash"))
        self.comboBox_line_dash.setItemText(4, _translate("Form", "dashdot"))
        self.comboBox_line_dash.setItemText(5, _translate("Form", "longdashdot"))
        self.label_28.setText(_translate("Form", "对应图表节点颜色"))
        self.line_color_Btn.setText(_translate("Form", "选择"))
        self.label_26.setText(_translate("Form", "填充纯色区域"))
        self.comboBox_fill.setItemText(0, _translate("Form", "none"))
        self.comboBox_fill.setItemText(1, _translate("Form", "tozeroy"))
        self.comboBox_fill.setItemText(2, _translate("Form", "tozerox"))
        self.comboBox_fill.setItemText(3, _translate("Form", "tonexty"))
        self.comboBox_fill.setItemText(4, _translate("Form", "tonextx"))
        self.comboBox_fill.setItemText(5, _translate("Form", "toself"))
        self.comboBox_fill.setItemText(6, _translate("Form", "tonext"))
        self.label_y_data.setText(_translate("Form", "y轴坐标数据"))
        self.y_data_Btn.setText(_translate("Form", "导入"))
        self.label_x_data.setText(_translate("Form", "x轴坐标数据"))
        self.x_data_Btn.setText(_translate("Form", "导入"))
        self.label_10.setText(_translate("Form", "y轴起点坐标"))
        self.label_11.setText(_translate("Form", "x轴起点坐标"))
        self.label_dx.setText(_translate("Form", "x轴坐标步进值"))
        self.label_dy.setText(_translate("Form", "y轴坐标步进值"))
        self.label_15.setText(_translate("Form", "透明度参数"))
        self.add_charts_Btn.setText(_translate("Form", "添加"))
        self.label.setText(_translate("Form", "点或线名称"))
        self.lineEdit_line_name.setText(_translate("Form", "ttt"))
        self.checkBox_scatter_connectgaps.setText(_translate("Form", "允许连接数据缺口"))
        self.label_7.setText(_translate("Form", "y轴坐标时间参数"))
        self.comboBox_ycalendar.setItemText(0, _translate("Form", "gregorian"))
        self.comboBox_ycalendar.setItemText(1, _translate("Form", "chinese"))
        self.comboBox_ycalendar.setItemText(2, _translate("Form", "coptic"))
        self.comboBox_ycalendar.setItemText(3, _translate("Form", "discworld"))
        self.comboBox_ycalendar.setItemText(4, _translate("Form", "ethiopian"))
        self.comboBox_ycalendar.setItemText(5, _translate("Form", "hebrew"))
        self.comboBox_ycalendar.setItemText(6, _translate("Form", "islamic"))
        self.comboBox_ycalendar.setItemText(7, _translate("Form", "julian"))
        self.comboBox_ycalendar.setItemText(8, _translate("Form", "mayan"))
        self.comboBox_ycalendar.setItemText(9, _translate("Form", "nanakshahi"))
        self.comboBox_ycalendar.setItemText(10, _translate("Form", "nepali"))
        self.comboBox_ycalendar.setItemText(11, _translate("Form", "persian"))
        self.comboBox_ycalendar.setItemText(12, _translate("Form", "jalali"))
        self.comboBox_ycalendar.setItemText(13, _translate("Form", "taiwan"))
        self.comboBox_ycalendar.setItemText(14, _translate("Form", "thai"))
        self.comboBox_ycalendar.setItemText(15, _translate("Form", "ummalqura"))
        self.comboBox_xcalendar.setItemText(0, _translate("Form", "gregorian"))
        self.comboBox_xcalendar.setItemText(1, _translate("Form", "chinese"))
        self.comboBox_xcalendar.setItemText(2, _translate("Form", "coptic"))
        self.comboBox_xcalendar.setItemText(3, _translate("Form", "discworld"))
        self.comboBox_xcalendar.setItemText(4, _translate("Form", "ethiopian"))
        self.comboBox_xcalendar.setItemText(5, _translate("Form", "hebrew"))
        self.comboBox_xcalendar.setItemText(6, _translate("Form", "islamic"))
        self.comboBox_xcalendar.setItemText(7, _translate("Form", "julian"))
        self.comboBox_xcalendar.setItemText(8, _translate("Form", "mayan"))
        self.comboBox_xcalendar.setItemText(9, _translate("Form", "nanakshahi"))
        self.comboBox_xcalendar.setItemText(10, _translate("Form", "nepali"))
        self.comboBox_xcalendar.setItemText(11, _translate("Form", "persian"))
        self.comboBox_xcalendar.setItemText(12, _translate("Form", "jalali"))
        self.comboBox_xcalendar.setItemText(13, _translate("Form", "taiwan"))
        self.comboBox_xcalendar.setItemText(14, _translate("Form", "thai"))
        self.comboBox_xcalendar.setItemText(15, _translate("Form", "ummalqura"))
        self.label_6.setText(_translate("Form", "x轴坐标时间参数"))
        self.groupBox_13.setTitle(_translate("Form", "hoverlabel"))
        self.label_17.setText(_translate("Form", "bgcolor"))
        self.hoverlabel_bgcolor_Btn.setText(_translate("Form", "选择"))
        self.label_18.setText(_translate("Form", "bordercolor"))
        self.hoverlabel_bordercolor_Btn.setText(_translate("Form", "选择"))
        self.groupBox_14.setTitle(_translate("Form", "font"))
        self.label_19.setText(_translate("Form", "family"))
        self.comboBox_hoverlabel_font_family.setItemText(0, _translate("Form", "Arial"))
        self.comboBox_hoverlabel_font_family.setItemText(1, _translate("Form", "Balto"))
        self.comboBox_hoverlabel_font_family.setItemText(2, _translate("Form", "Courier New"))
        self.comboBox_hoverlabel_font_family.setItemText(3, _translate("Form", "Droid Sans"))
        self.comboBox_hoverlabel_font_family.setItemText(4, _translate("Form", "Droid  Serif"))
        self.comboBox_hoverlabel_font_family.setItemText(5, _translate("Form", "Droid Sans Mono"))
        self.comboBox_hoverlabel_font_family.setItemText(6, _translate("Form", "Gravitas One"))
        self.comboBox_hoverlabel_font_family.setItemText(7, _translate("Form", "Old Standard TT"))
        self.comboBox_hoverlabel_font_family.setItemText(8, _translate("Form", "Open Sans"))
        self.comboBox_hoverlabel_font_family.setItemText(9, _translate("Form", "Overpass"))
        self.comboBox_hoverlabel_font_family.setItemText(10, _translate("Form", "PT Sans Narrow"))
        self.comboBox_hoverlabel_font_family.setItemText(11, _translate("Form", "Raleway"))
        self.comboBox_hoverlabel_font_family.setItemText(12, _translate("Form", "Times New Roman"))
        self.label_22.setText(_translate("Form", "size"))
        self.label_25.setText(_translate("Form", "color"))
        self.hoverlabel_font_color_Btn.setText(_translate("Form", "选择"))
        self.label_4.setText(_translate("Form", "text"))
        self.label_20.setText(_translate("Form", "互动时鼠标指针显示的参数"))
        self.comboBox_hoverinfo.setItemText(0, _translate("Form", "all"))
        self.comboBox_hoverinfo.setItemText(1, _translate("Form", "x"))
        self.comboBox_hoverinfo.setItemText(2, _translate("Form", "y"))
        self.comboBox_hoverinfo.setItemText(3, _translate("Form", "z"))
        self.comboBox_hoverinfo.setItemText(4, _translate("Form", "text"))
        self.comboBox_hoverinfo.setItemText(5, _translate("Form", "name"))
        self.comboBox_hoverinfo.setItemText(6, _translate("Form", "none"))
        self.comboBox_hoverinfo.setItemText(7, _translate("Form", "x+y"))
        self.comboBox_hoverinfo.setItemText(8, _translate("Form", "x+y+name"))
        self.comboBox_hoverinfo.setItemText(9, _translate("Form", "x+y+text"))
        self.comboBox_hoverinfo.setItemText(10, _translate("Form", "x+y+z+text"))
        self.comboBox_hoverinfo.setItemText(11, _translate("Form", "y+z"))
        self.comboBox_hoverinfo.setItemText(12, _translate("Form", "x+z"))
        self.comboBox_hoverinfo.setItemText(13, _translate("Form", "x+z+y"))
        self.label_21.setText(_translate("Form", "互动时鼠标指针显示的模式"))
        self.comboBox_hoveron.setItemText(0, _translate("Form", "points"))
        self.comboBox_hoveron.setItemText(1, _translate("Form", "fills"))
        self.comboBox_hoveron.setItemText(2, _translate("Form", "points+fills"))
        self.label_14.setText(_translate("Form", "“文本”元素位置"))
        self.comboBox_textposition.setItemText(0, _translate("Form", "middle center"))
        self.comboBox_textposition.setItemText(1, _translate("Form", "top left"))
        self.comboBox_textposition.setItemText(2, _translate("Form", "top center"))
        self.comboBox_textposition.setItemText(3, _translate("Form", "top right"))
        self.comboBox_textposition.setItemText(4, _translate("Form", "middle left"))
        self.comboBox_textposition.setItemText(5, _translate("Form", "middle right"))
        self.comboBox_textposition.setItemText(6, _translate("Form", "bottom left"))
        self.comboBox_textposition.setItemText(7, _translate("Form", "bottom center"))
        self.comboBox_textposition.setItemText(8, _translate("Form", "bottom right"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("Form", "data参数"))
        self.groupBox_5.setTitle(_translate("Form", "title"))
        self.groupBox_15.setTitle(_translate("Form", "font"))
        self.label_27.setText(_translate("Form", "family"))
        self.comboBox_layout_title_font_family.setItemText(0, _translate("Form", "Arial"))
        self.comboBox_layout_title_font_family.setItemText(1, _translate("Form", "Balto"))
        self.comboBox_layout_title_font_family.setItemText(2, _translate("Form", "Courier New"))
        self.comboBox_layout_title_font_family.setItemText(3, _translate("Form", "Droid Sans"))
        self.comboBox_layout_title_font_family.setItemText(4, _translate("Form", "Droid  Serif"))
        self.comboBox_layout_title_font_family.setItemText(5, _translate("Form", "Droid Sans Mono"))
        self.comboBox_layout_title_font_family.setItemText(6, _translate("Form", "Gravitas One"))
        self.comboBox_layout_title_font_family.setItemText(7, _translate("Form", "Old Standard TT"))
        self.comboBox_layout_title_font_family.setItemText(8, _translate("Form", "Open Sans"))
        self.comboBox_layout_title_font_family.setItemText(9, _translate("Form", "Overpass"))
        self.comboBox_layout_title_font_family.setItemText(10, _translate("Form", "PT Sans Narrow"))
        self.comboBox_layout_title_font_family.setItemText(11, _translate("Form", "Raleway"))
        self.comboBox_layout_title_font_family.setItemText(12, _translate("Form", "Times New Roman"))
        self.label_31.setText(_translate("Form", "size"))
        self.label_33.setText(_translate("Form", "color"))
        self.layout_title_font_color_Btn.setText(_translate("Form", "选择"))
        self.label_37.setText(_translate("Form", "text"))
        self.label_40.setText(_translate("Form", "y"))
        self.label_39.setText(_translate("Form", "x"))
        self.label_42.setText(_translate("Form", "yanchor"))
        self.comboBox_layout_title_xanchor.setItemText(0, _translate("Form", "auto"))
        self.comboBox_layout_title_xanchor.setItemText(1, _translate("Form", "left"))
        self.comboBox_layout_title_xanchor.setItemText(2, _translate("Form", "center"))
        self.comboBox_layout_title_xanchor.setItemText(3, _translate("Form", "right"))
        self.label_41.setText(_translate("Form", "xanchor"))
        self.comboBox_layout_title_yanchor.setItemText(0, _translate("Form", "auto"))
        self.comboBox_layout_title_yanchor.setItemText(1, _translate("Form", "top"))
        self.comboBox_layout_title_yanchor.setItemText(2, _translate("Form", "middle"))
        self.comboBox_layout_title_yanchor.setItemText(3, _translate("Form", "bottom"))
        self.label_3.setText(_translate("Form", "pad"))
        self.comboBox_layout_title_pad.setItemText(0, _translate("Form", "b"))
        self.comboBox_layout_title_pad.setItemText(1, _translate("Form", "l"))
        self.comboBox_layout_title_pad.setItemText(2, _translate("Form", "r"))
        self.comboBox_layout_title_pad.setItemText(3, _translate("Form", "t"))
        self.groupBox_7.setTitle(_translate("Form", "margin"))
        self.checkBox_8.setText(_translate("Form", "autoexpand"))
        self.label_52.setText(_translate("Form", "1"))
        self.label_53.setText(_translate("Form", "r"))
        self.label_54.setText(_translate("Form", "t"))
        self.label_55.setText(_translate("Form", "b"))
        self.label_56.setText(_translate("Form", "pad"))
        self.groupBox_6.setTitle(_translate("Form", "legend"))
        self.label_43.setText(_translate("Form", "x"))
        self.label_44.setText(_translate("Form", "y"))
        self.label_45.setText(_translate("Form", "bordercolor"))
        self.pushButton_2.setText(_translate("Form", "PushButton"))
        self.label_46.setText(_translate("Form", "borderwidth"))
        self.comboBox_11.setItemText(0, _translate("Form", "zoom"))
        self.comboBox_11.setItemText(1, _translate("Form", "pan"))
        self.comboBox_11.setItemText(2, _translate("Form", "select"))
        self.comboBox_11.setItemText(3, _translate("Form", "lasso"))
        self.comboBox_11.setItemText(4, _translate("Form", "orbit"))
        self.comboBox_11.setItemText(5, _translate("Form", "turntable"))
        self.comboBox_11.setItemText(6, _translate("Form", "False"))
        self.groupBox_8.setTitle(_translate("Form", "xaxis"))
        self.checkBox.setText(_translate("Form", "showline"))
        self.checkBox_2.setText(_translate("Form", "zeroline"))
        self.label_66.setText(_translate("Form", "overlaying"))
        self.checkBox_3.setText(_translate("Form", "autotick"))
        self.label_72.setText(_translate("Form", "tickfont"))
        self.checkBox_5.setText(_translate("Form", "showgrid"))
        self.groupBox_9.setTitle(_translate("Form", "rangeslider"))
        self.checkBox_6.setText(_translate("Form", "autorange"))
        self.label_80.setText(_translate("Form", "range"))
        self.checkBox_11.setText(_translate("Form", "visible"))
        self.checkBox_12.setText(_translate("Form", "y"))
        self.label_77.setText(_translate("Form", "bgcolor"))
        self.pushButton_9.setText(_translate("Form", "PushButton"))
        self.label_78.setText(_translate("Form", "bordercolor"))
        self.pushButton_10.setText(_translate("Form", "PushButton"))
        self.label_79.setText(_translate("Form", "borderwidth"))
        self.label_81.setText(_translate("Form", "thickness"))
        self.groupBox_10.setTitle(_translate("Form", "rangeslider"))
        self.label_84.setText(_translate("Form", "visible"))
        self.label_85.setText(_translate("Form", "buttons"))
        self.label_86.setText(_translate("Form", "x"))
        self.label_87.setText(_translate("Form", "y"))
        self.label_91.setText(_translate("Form", "font"))
        self.label_92.setText(_translate("Form", "yanchor"))
        self.label_93.setText(_translate("Form", "xanchor"))
        self.groupBox_11.setTitle(_translate("Form", "buttons"))
        self.checkBox_7.setText(_translate("Form", "visible"))
        self.label_97.setText(_translate("Form", "label"))
        self.label_96.setText(_translate("Form", "stepmode"))
        self.comboBox_17.setItemText(0, _translate("Form", "backward"))
        self.comboBox_17.setItemText(1, _translate("Form", "todate"))
        self.label_95.setText(_translate("Form", "count"))
        self.label_94.setText(_translate("Form", "step"))
        self.comboBox_16.setItemText(0, _translate("Form", "month"))
        self.comboBox_16.setItemText(1, _translate("Form", "year"))
        self.comboBox_16.setItemText(2, _translate("Form", "day"))
        self.comboBox_16.setItemText(3, _translate("Form", "hour"))
        self.comboBox_16.setItemText(4, _translate("Form", "minute"))
        self.comboBox_16.setItemText(5, _translate("Form", "second"))
        self.comboBox_16.setItemText(6, _translate("Form", "all"))
        self.label_88.setText(_translate("Form", "borderwidth"))
        self.label_89.setText(_translate("Form", "bordercolor"))
        self.pushButton_11.setText(_translate("Form", "PushButton"))
        self.label_90.setText(_translate("Form", "bgcolor"))
        self.pushButton_12.setText(_translate("Form", "PushButton"))
        self.checkBox_9.setText(_translate("Form", "visible"))
        self.groupBox.setTitle(_translate("Form", "title"))
        self.groupBox_16.setTitle(_translate("Form", "font"))
        self.label_35.setText(_translate("Form", "family"))
        self.comboBox_hoverlabel_font_family_3.setItemText(0, _translate("Form", "Arial"))
        self.comboBox_hoverlabel_font_family_3.setItemText(1, _translate("Form", "Balto"))
        self.comboBox_hoverlabel_font_family_3.setItemText(2, _translate("Form", "Courier New"))
        self.comboBox_hoverlabel_font_family_3.setItemText(3, _translate("Form", "Droid Sans"))
        self.comboBox_hoverlabel_font_family_3.setItemText(4, _translate("Form", "Droid  Serif"))
        self.comboBox_hoverlabel_font_family_3.setItemText(5, _translate("Form", "Droid Sans Mono"))
        self.comboBox_hoverlabel_font_family_3.setItemText(6, _translate("Form", "Gravitas One"))
        self.comboBox_hoverlabel_font_family_3.setItemText(7, _translate("Form", "Old Standard TT"))
        self.comboBox_hoverlabel_font_family_3.setItemText(8, _translate("Form", "Open Sans"))
        self.comboBox_hoverlabel_font_family_3.setItemText(9, _translate("Form", "Overpass"))
        self.comboBox_hoverlabel_font_family_3.setItemText(10, _translate("Form", "PT Sans Narrow"))
        self.comboBox_hoverlabel_font_family_3.setItemText(11, _translate("Form", "Raleway"))
        self.comboBox_hoverlabel_font_family_3.setItemText(12, _translate("Form", "Times New Roman"))
        self.label_36.setText(_translate("Form", "size"))
        self.label_38.setText(_translate("Form", "color"))
        self.hoverlabel_font_color_Btn_3.setText(_translate("Form", "选择"))
        self.label_9.setText(_translate("Form", "text"))
        self.checkBox_10.setText(_translate("Form", "showticklabels"))
        self.label_5.setText(_translate("Form", "color"))
        self.pushButton_5.setText(_translate("Form", "PushButton"))
        self.label_59.setText(_translate("Form", "tickformat"))
        self.comboBox_4.setItemText(0, _translate("Form", ","))
        self.comboBox_4.setItemText(1, _translate("Form", "YYYY-MM-DD"))
        self.label_60.setText(_translate("Form", "ticksuffix"))
        self.label_61.setText(_translate("Form", "tickprefix"))
        self.label_62.setText(_translate("Form", "type"))
        self.comboBox_12.setItemText(0, _translate("Form", "-"))
        self.comboBox_12.setItemText(1, _translate("Form", "linear"))
        self.comboBox_12.setItemText(2, _translate("Form", "log"))
        self.comboBox_12.setItemText(3, _translate("Form", "date"))
        self.comboBox_12.setItemText(4, _translate("Form", "category"))
        self.comboBox_12.setItemText(5, _translate("Form", "multicategory"))
        self.label_63.setText(_translate("Form", "linecolor"))
        self.pushButton_6.setText(_translate("Form", "PushButton"))
        self.label_64.setText(_translate("Form", "linewidth"))
        self.label_67.setText(_translate("Form", "rangemode"))
        self.comboBox_13.setItemText(0, _translate("Form", "normal"))
        self.comboBox_13.setItemText(1, _translate("Form", "tozero"))
        self.label_68.setText(_translate("Form", "side"))
        self.comboBox_14.setItemText(0, _translate("Form", "top"))
        self.comboBox_14.setItemText(1, _translate("Form", "bottom"))
        self.comboBox_14.setItemText(2, _translate("Form", "left"))
        self.comboBox_14.setItemText(3, _translate("Form", "right"))
        self.checkBox_4.setText(_translate("Form", "ticks"))
        self.comboBox_15.setItemText(1, _translate("Form", "outside(外部)"))
        self.comboBox_15.setItemText(2, _translate("Form", "inside(内部)"))
        self.label_69.setText(_translate("Form", "ticklen"))
        self.label_70.setText(_translate("Form", "tickwidth"))
        self.label_71.setText(_translate("Form", "tickcolor"))
        self.pushButton_7.setText(_translate("Form", "PushButton"))
        self.label_73.setText(_translate("Form", "nticks"))
        self.label_75.setText(_translate("Form", "gridcolor"))
        self.pushButton_8.setText(_translate("Form", "PushButton"))
        self.label_76.setText(_translate("Form", "gridwidth"))
        self.label_48.setText(_translate("Form", "height"))
        self.label_47.setText(_translate("Form", "width"))
        self.label_49.setText(_translate("Form", "paper_bgcolor"))
        self.pushButton_3.setText(_translate("Form", "PushButton"))
        self.label_50.setText(_translate("Form", "plot_bgcolor"))
        self.pushButton_4.setText(_translate("Form", "PushButton"))
        self.label_58.setText(_translate("Form", "dragmode"))
        self.comboBox_3.setItemText(0, _translate("Form", "zoom"))
        self.comboBox_3.setItemText(1, _translate("Form", "pan"))
        self.comboBox_3.setItemText(2, _translate("Form", "select"))
        self.comboBox_3.setItemText(3, _translate("Form", "lasso"))
        self.comboBox_3.setItemText(4, _translate("Form", "orbit"))
        self.comboBox_3.setItemText(5, _translate("Form", "turntable"))
        self.comboBox_3.setItemText(6, _translate("Form", "False"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "layout参数"))
        self.confirm_Btn.setText(_translate("Form", "确定"))
        self.preview_Btn.setText(_translate("Form", "预览"))
        self.cancel_Btn.setText(_translate("Form", "取消"))

