# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_savefile.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_file = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_file.setObjectName("lineEdit_file")
        self.horizontalLayout_2.addWidget(self.lineEdit_file)
        self.file_Btn = QtWidgets.QPushButton(Dialog)
        self.file_Btn.setObjectName("file_Btn")
        self.horizontalLayout_2.addWidget(self.file_Btn)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_sep = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_sep.setObjectName("lineEdit_sep")
        self.verticalLayout_2.addWidget(self.lineEdit_sep)
        self.lineEdit_na_rep = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_na_rep.setObjectName("lineEdit_na_rep")
        self.verticalLayout_2.addWidget(self.lineEdit_na_rep)
        self.lineEdit_encoding = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_encoding.setObjectName("lineEdit_encoding")
        self.verticalLayout_2.addWidget(self.lineEdit_encoding)
        self.comboBox_compression = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_compression.sizePolicy().hasHeightForWidth())
        self.comboBox_compression.setSizePolicy(sizePolicy)
        self.comboBox_compression.setObjectName("comboBox_compression")
        self.comboBox_compression.addItem("")
        self.comboBox_compression.addItem("")
        self.comboBox_compression.addItem("")
        self.comboBox_compression.addItem("")
        self.comboBox_compression.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_compression)
        self.lineEdit_decimal = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_decimal.setObjectName("lineEdit_decimal")
        self.verticalLayout_2.addWidget(self.lineEdit_decimal)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.save_Btn = QtWidgets.QPushButton(Dialog)
        self.save_Btn.setObjectName("save_Btn")
        self.horizontalLayout_7.addWidget(self.save_Btn)
        spacerItem = QtWidgets.QSpacerItem(160, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.Cancel_Btn = QtWidgets.QPushButton(Dialog)
        self.Cancel_Btn.setObjectName("Cancel_Btn")
        self.horizontalLayout_7.addWidget(self.Cancel_Btn)
        self.gridLayout.addLayout(self.horizontalLayout_7, 4, 0, 1, 2)
        self.checkBox_index = QtWidgets.QCheckBox(Dialog)
        self.checkBox_index.setChecked(False)
        self.checkBox_index.setObjectName("checkBox_index")
        self.gridLayout.addWidget(self.checkBox_index, 2, 0, 1, 1)
        self.checkBox_header = QtWidgets.QCheckBox(Dialog)
        self.checkBox_header.setChecked(True)
        self.checkBox_header.setObjectName("checkBox_header")
        self.gridLayout.addWidget(self.checkBox_header, 2, 1, 1, 1)
        self.label.setBuddy(self.lineEdit_sep)
        self.label_2.setBuddy(self.lineEdit_na_rep)
        self.label_3.setBuddy(self.lineEdit_encoding)
        self.label_4.setBuddy(self.comboBox_compression)
        self.label_5.setBuddy(self.lineEdit_decimal)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "保存"))
        self.file_Btn.setText(_translate("Dialog", "选择路径"))
        self.label.setText(_translate("Dialog", "输出文件的字段分隔符"))
        self.label_2.setText(_translate("Dialog", "缺失值表示"))
        self.label_3.setText(_translate("Dialog", "编码方式"))
        self.label_4.setText(_translate("Dialog", "压缩"))
        self.label_5.setText(_translate("Dialog", "小数点识别符"))
        self.lineEdit_sep.setText(_translate("Dialog", ","))
        self.lineEdit_encoding.setText(_translate("Dialog", "utf-8"))
        self.comboBox_compression.setItemText(0, _translate("Dialog", "None"))
        self.comboBox_compression.setItemText(1, _translate("Dialog", "gzip"))
        self.comboBox_compression.setItemText(2, _translate("Dialog", "bz2"))
        self.comboBox_compression.setItemText(3, _translate("Dialog", "zip"))
        self.comboBox_compression.setItemText(4, _translate("Dialog", "xz"))
        self.lineEdit_decimal.setText(_translate("Dialog", "."))
        self.save_Btn.setText(_translate("Dialog", "保存"))
        self.Cancel_Btn.setText(_translate("Dialog", "取消"))
        self.checkBox_index.setText(_translate("Dialog", "是否写入索引"))
        self.checkBox_header.setText(_translate("Dialog", "是否有列名"))

